apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: training-snakes
  namespace: default
  labels:
    app: training-snakes
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  selector:
    matchLabels:
      app: training-snakes
  template:
    metadata:
      labels:
        app: training-snakes
    spec:
      containers:
      - name: training-snakes
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        resources:
          limits:
            cpu: "0.5"
            memory: 500M
          requests:
            cpu: "0.25"
            memory: 250M
        ports:
          - containerPort: 5000