apiVersion: v1
kind: Service
metadata:
  name: training-snakes
  namespace: default
spec:
  selector:
    app: training-snakes
  ports:
    - name: http
      protocol: 'TCP'
      port: 80
      targetPort: 5000
